FROM node:15

WORKDIR /app

ARG NODE_ENV
ARG MAIL_SERVICE
ARG MAIL_USER
ARG MAIL_PASSWORD
ARG USE_MAIL
ARG TOKEN_SECRET
ARG PORT
ARG DEV_HOST
ARG PRODUCTION_HOST
ARG DB_USERNAME
ARG DB_PASSWORD
ARG DB_DATABASE
ARG DB_HOST
ARG DB_PORT
ARG DEV_DATABASE_URL
ENV NODE_ENV $NODE_ENV
ENV MAIL_SERVICE $MAIL_SERVICE
ENV MAIL_USER $MAIL_USER
ENV MAIL_PASSWORD $MAIL_PASSWORD
ENV USE_MAIL $USE_MAIL
ENV TOKEN_SECRET $TOKEN_SECRET
ENV PORT $PORT
ENV DEV_HOST $DEV_HOST
ENV PRODUCTION_HOST $PRODUCTION_HOST
ENV DB_USERNAME $DB_USERNAME
ENV DB_PASSWORD $DB_PASSWORD
ENV DB_DATABASE $DB_DATABASE
ENV DB_HOST $DB_HOST
ENV DB_PORT $DB_PORT
ENV DB_DIALECT $DB_DIALECT
ENV DEV_DATABASE_URL $DEV_DATABASE_URL
# Install app dependencies
# A wildcard is used to ensure both package.json AND package-lock.json are copied
# where available (npm@5+)
COPY package*.json ./
COPY tsconfig.json ./

# Bundle app source
COPY . .

RUN npm ci --quiet && npm run build
# If you are building your code for production
# RUN npm ci --only=production


EXPOSE 8000

CMD [ "node", "./build/bin/www.js"]